##### Numpy -> biblioteca de cálculos em arrays

In [20]:
import numpy as np 
lista = [1,2,3]
print(lista)
print(type(lista))
listaP = ["ve",1]

[1, 2, 3]
<class 'list'>


In [21]:
array = np.array(listaP)#transforma em array
print(array)
print(type(array)) 

['ve' '1']
<class 'numpy.ndarray'>


In [22]:
matriz = [ [ 1,2,3],[4,5,6],[7,8,9]]
print(matriz)
print("------------------")
mat_numpy=np.array(matriz)
print(mat_numpy)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Se usa .shape para e ro formato da matriz
ndim -> número de dimensões 
np.reshape -> redimensiona array

In [23]:

print(mat_numpy.shape)

(3, 3)


Redimensionando arrays

In [24]:
my_array = np.array([1,2,3,4,5,6,7,8])
print(my_array)
print('\n---',my_array.reshape((2,4)))
np.reshape(my_array, (2,4))

[1 2 3 4 5 6 7 8]

--- [[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# criar array com numeros de 0 a 9

In [25]:
matriz = [1,2,3,4,5,6,7,8,9]
teste = np.array(matriz)
n = teste.reshape(3,3)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array de 0 a 100 pulando de 10 a 10


In [26]:
#np.arange(start,stop,step)

teste=np.arange(0,101,10)
print(teste)

[  0  10  20  30  40  50  60  70  80  90 100]


In [27]:
#matrizes com valores unicos 
print(np.zeros((2,2)))
print("----------")
print(np.ones((5,2)))

#np full cria com valores passados
print("-----------")
np.full((5,2),6) #linhas, colunas, o quw vai preencher

[[0. 0.]
 [0. 0.]]
----------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
-----------


array([[6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6]])

In [28]:
#matriz boleana 10*10 com valores true

np.full((10,10),True)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [29]:
#linspace, valores igualmente espaçados

print(np.linspace(1,6,9))
print("------------")
np.linspace(2,3,5)

[1.    1.625 2.25  2.875 3.5   4.125 4.75  5.375 6.   ]
------------


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [30]:
#valores aleatorios
teste=np.random.rand(2,2)#numeros ponto flutuante
print(teste)



[[0.71155404 0.18861472]
 [0.09878071 0.682833  ]]


In [31]:
np.random.randint(0,10,10)#inteiro

array([8, 0, 6, 4, 5, 3, 1, 1, 9, 0])

In [32]:
#.max()
#.min()
#argmax() -> indice valor maximo
#argmin ()-> indice do menor valor
np.argmax(teste)

0

In [33]:
matriz = [11,22,34,44,75,68,78,88,89]
teste = np.array(matriz)
n = teste.reshape(3,3)
print(n)

t = len(n[0])

print("tamanho",t)
print(np.shape(n))
#teste[:5]

#teste[0:10:2]

[[11 22 34]
 [44 75 68]
 [78 88 89]]
tamanho 3
(3, 3)


In [34]:
# identificar numeros impares de uma rray 3/3 e substituir por 0

matriz = np.random.randint(0,10,12)#n inicial, n final, qtd de numeros
n = np.array(matriz).reshape((3,4))
print(n)
print("--------------")
impar = (n%2!=0)
n[impar]=0
print(n)
#matriz.reshape(3,3)
#print(matriz)

[[2 9 4 1]
 [5 2 7 8]
 [3 0 7 1]]
--------------
[[2 0 4 0]
 [0 2 0 8]
 [0 0 0 0]]


Crie um array de 2 linhas e 3 colunas e faça as seguintes operações:
Faça um reshape de 3 linhas e 2 colunas;
Some a primeira linha por 5;
Multiplique a segunda linha por 3;
E divida a segunda coluna por 2.

In [35]:
matriz = np.random.randint(0,10,6)
n = np.array(matriz).reshape((2,3))
i = n.reshape(3,2)
print(i)
print("Soma:")
soma = i[0]+5
print(soma)
multiplicacao = i[1]*3
print("Multi",multiplicacao)
i[:,1] = i[:,1]/2



[[4 3]
 [6 9]
 [4 7]]
Soma:
[9 8]
Multi [18 27]


Crie uma função que recebe um número inteiro n e retorna um array n x n do NumPy , com as seguintes regras:
Os elementos da diagonal principal devem valer 1
Os elementos da diagonal secundária devem valer 2
Os demais elementos devem valer 0
Quando um elemento pertence às duas diagonais (isso só ocorre se n for ímpar), ele deve valer 3

In [36]:
n = int(input("Insira o tamanho da matriz: "))
l=0
c=0
matriz= np.zeros((n,n))
for i in range(n):
    matriz[l][c]=1
    l+=1
    c+=1


t = len(matriz[0])
l=0
c=t-1
for i in range(t):
    matriz[l][c]=2
    l+=1
    c-=1
print(matriz)

ValueError: invalid literal for int() with base 10: ''

In [ ]:
n = int(input("Insira o tamanho da matriz: "))
matriz= np.zeros((n,n))
for i in range(n):
    matriz[i,i]=1
    matriz[i,n-1-i]+=2

print(matriz)

[[1. 0. 0. 2.]
 [0. 1. 2. 0.]
 [0. 2. 1. 0.]
 [2. 0. 0. 1.]]


In [ ]:
n = 3
matriz = np.random.randint(0,10,(n,n))
m= matriz.reshape((3,3)) #coloca em formato de tamanho
print(m,"-")
nova = np.zeros((n,n)) #nova matriz com zeros

for i in range(n):
    for j in range(n):
        if i != 0: 
            nova[i,j] +=m[i-1,j]#some linha de baixo
        if j!=0:
            nova[i,j] += m[i,j-1]#some coluna de tras
        if i != n-1:
            nova[i,j]+= m[i+1,j] #some linha de baixo
        if j != n-1:
            nova[i,j]+= m[i,j+1] # some coluna de cima

print(nova)
          




[[1 2 8]
 [3 1 1]
 [4 1 2]] -
[[ 5. 10.  3.]
 [ 6.  7. 11.]
 [ 4.  7.  2.]]


In [19]:
n = 3
matriz = np.random.randint(0,10,(n,n))
m= matriz.reshape((3,3))
nova = np.empty_like(m)

print(m)
print()
print(nova)

[[3 4 7]
 [4 7 2]
 [4 8 3]]

[[7 5 9]
 [9 8 2]
 [6 8 9]]
